language: cpp
script: make release-static
dist: xenial
before_install:
  - sudo apt-get install libboost-all-dev -y
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libssl-dev
      - libboost-all-dev
      - build-essential
      - cmake
      - pkg-config
      - libunbound-dev
